### ISSUE TITLE
Feature request: sync of LFO's

### ISSUE THREAD

**Issue by magnetophon** [ryukau/LV2Plugins#10]
Thanks for the great plugins!
They sound wonderful and have a very user-friendly interface.
I love the keyboard shortcuts and the built in help!

Have you considered adding a sync option for the LFO's?
Optimally, you could choose to sync to either note start or beat/bar.

**Comment by ryukau** [comment]
Hi, magnetophon.

Which plugin do you want to have LFO sync option?

L4Reverb and LatticeReverb are technically not using LFO, so I will not change those 2. I think it's nice to have sync options for other plugins.

I didn't put much effort on LFOs because I usually draw automation instead of using LFO.

**Comment by magnetophon** [comment]
Hi @ryukau,

Yes, all of the plugins where it would make sense, please!  :)

**Comment by ryukau** [comment]
Thanks for clarification.

It seems like you don't have specific use case, so I will not change following plugins.

- LightPadSynth: Retrigger is omitted for efficiency.
- FDNCymbal: It's better to make a new one.

I'll gradually make changes for the rest of plugins.

**Comment by magnetophon** [comment]
I see you have been working hard on this, thank you!
TrapezoidSynth now has what I meant with LFO sync; you have called it retrigger.  :)
The controls that you call sync are also very useful.

Will the other synths also get LFO retrigger?
Not that I am impatient, you've given us enough new toys to play with!
I just wanted to check if we had a miscommunication, with the sync/retrigger naming thing.

**Comment by magnetophon** [comment]
I also mentioned syncing (=retriggering) to the beat instead of to the note, but I didn't explain what I meant. Maybe "locking to the beat" is a better term. 
[This video](https://youtu.be/CYJ2J07xqhY?t=171) explains it better than I could. 
What they call Beat1 mode is probably hard to implement, but Beat2 might be doable.

**Comment by magnetophon** [comment]
May I also say kudo's for the strict versioning approach, even before the first release!

**Comment by ryukau** [comment]
I use sync as short for tempo sync, and retrigger as reset at note-on. Following image might helps to make it clear about retrigger.

![lfo_retrigger](https://user-images.githubusercontent.com/6243462/83956012-2fdf2200-a894-11ea-9b30-100bf9a3f1b1.png)

Remaining synths except CubicPadSynth are all polyphonic and using global LFO. For those synths, I have to add LFO to every note class to enable retrigger. So I will not implement retrigger for efficiency. CubicPadSynth already has retrigger and tempo sync.

By watching the video, Beat1 just interplates LFO frequency inside of audio buffers, and Beat2 is resetting LFO phase when rate parameter is changed. All of my synth interplates lfo frequency (rate), so they only works as Beat1 mode.

The synth in the video also keeps LFO phase in sync, which I think great. Plugins in this repo don't keep LFO phase in sync, and that's probably the missing part. I'll work on it.

Just in case, you can change LFO frequency by freq parameter in LFO/Modulation section, even if sync is checked.

**Comment by magnetophon** [comment]
Thanks for te explanation. I understood what retrigger does, but I didn't realize you had global LFO's in your poly synths.  makes sense.

It also seems retrigger is in more synths than I thought. Great, thanks!
I had only seen the commit message for TrapezoidSynth, sorry!

It would be cool if you could implement the "lfo in phase with the beat, independent of note", like Beat2 mode in the video!

I think the tricky part about Beat1 mode is interpolating but still ending up in phase with the beat.
If you could pull that off as well, even better.

But the note retrigger you have now makes these synths already way more useful!  :partying_face:

**Comment by ryukau** [comment]
I think "lfo in phase with the beat, independent of note" can be done with setting retrigger off and sync on. Perhaps my English is a bit off here, so let me know if I'm misunderstanding.

I'll add phase control to TrapezoidSynth, but no more expansion. I'm a bit cautious here because expanding a plugin adds a burden of migration for existing project. I'm planning to make bass synth with better LFO, but it needs more ground work. So low priority for now.

**Comment by magnetophon** [comment]
> I think "lfo in phase with the beat, independent of note" can be done with setting retrigger off and sync on. Perhaps my English is a bit off here, so let me know if I'm misunderstanding.

As far as I know, when you do that, the LFO is free-running, in other words, never gets retriggered, right?
So the phase of the LFO relative to the beat/bar position of the DAW depends on when you start the DAW.

To do what I am talking about, you need to get the position in the song from the daw, and calculate the phase based on that.

Again, not an important feature, but a nice one to have!

**Comment by ryukau** [comment]
I get it. So it's basically hard-syncing LFO by using start of a beat as trigger signal.

I have an idea for Beat1.

Synced LFO is deterministic. So assuming initial phase is 0, we can compute LFO phase in Beat2 as following equation:

```
B_2(t) = fmod(t, λ_t) / λ_s
```

where

- B2: Beat2 LFO phase function. Output is normalized in [0, 1).
- t: Time in seconds from the start of a song.
- λ_s: Sync period in seconds. Rate parameter in the video.
- λ_t: Trigger period in seconds.

Let B_1(t) as Beat1 phase function, so it can be written as:

```
B_1(t) = B_2(t) + D(t).
```

There are some freedom to design D(t). The constaints are `B_2(0) + D(0) = 0` and `B_2(λ_t) + D(λ_t) = 1`. In other words, LFO phase must be 0 at the start of a beat and 1 at the end of a beat. Also it should be smooth.

Below is a visualization of B_1 and B_2.

![lfo_beat1_beat2](https://user-images.githubusercontent.com/6243462/83969000-111a7300-a908-11ea-9241-ced2dc5e6e3b.png)

A straight forward implementation is linear interpolation of B_2 to full phase function B_full:

```
B_full(t) = fmod(t, λ_t) / λ_t
D_linear(t) = B_2(t) + B_full(t) * (B_full(t) - B_2(t))
```

Notice that B_full goes from 0 to 1 in period of λ_t, which is the length of a beat in seconds.

But what happens when rate is changed? It certainly cause discontinuity. One trick I came up is to use 2 B_1 functions, then linear interpolates them in a buffer. Let the rate in previous buffer as f_prev, and the rate in current buffer as f_curr.

```
λ_s_prev = 1 / f_prev
λ_s_curr = 1 / f_curr

B_2_prev = fmod(t, λ_t) / λ_s_prev
B_2_curr = fmod(t, λ_t) / λ_s_curr

D_linear_prev(t) = B_2_prev(t) + B_full(t) * (B_full(t) - B_2_prev(t))
D_linear_curr(t) = B_2_curr(t) + B_full(t) * (B_full(t) - B_2_curr(t))

B_1_prev(t) = B_2_prev(t) + D_linear_prev(t)
B_1_curr(t) = B_2_curr(t) + D_linear_curr(t)

// frame is number of samples spent in a buffer.
mix = frame / bufferSize
phase = B_1_prev(t) + mix * (B_1_curr(t) - B_1_prev(t))
```

If the bufferSize is large, we can get somewhat smooth phase transition, I think. It needs to be tested.

It's also possible to make `mix` not to be dependent to bufferSize. I did the similar trick in EsPhaser.

---

There's most likely a better approach. I think modulating phase incrementation will be more clean. Will look into it. If anyone reading this comment have an idea, please let me know.

**Comment by magnetophon** [comment]
Cool that you are seriously considering this!

> I get it. So it's basically hard-syncing LFO by using start of a beat as trigger signal.

The end result of that would be very similar to wat we want, but if you would set a speed that is not an integer multiple of the song speed, you still want the lfo to be continuous, and not reset every bar.


> One trick I came up is to use 2 B_1 functions, then linear interpolates them in a buffer.

If I understand correctly, you suggest a crossfade between 2 lfo's to get back into phase, right?

I think that would work, but you will sometimes end up with a value bigger than one lfo at it's max, correct?
Mostly that is not a problem, but with "unstable" algorithms, like TrapezoidSynth, it can be.
By unstable, I mean that in some cases the sound changes a lot with small tweaks.

**Comment by ryukau** [comment]
I'd like to be precise here, so I'm going to be verbose for first problem.

The upper numeral of syncing beat is the period of bar to sync LFO phase.

For example:

- 1/3, 1/4, 1/7 sync at the start of every bar.
- 2/3, 2/4, 2/7 sync at the start of every 2 bar.
- 3/3, 3/4, 3/7 sync at the start of every 3 bar.

and so on.

In this way, user can control which bar to sync.

For example:

- 1/2 syncs at every bar.
- 2/4 syncs at every 2 bar.
- 3/6 syncs at every 3 bar.

and so on.

I'm currently using freq parameter as multiplier when sync is checked. I guess following condition is sufficient to switch to sync at bar or not.

```
if (multiplier == 1)
  syncAtBar(upperNumeral);
else
  freeRunning();
```

It's probably better to use limited set of beat, like typical 1/n, 1/n triplet, 1/n dot, where `n = {1,2,4,8,16}`. So the upper numeral will be limited to 1 and 3. But this is out of scope on existing synths.

---

Yes, crossfade is better term. I was missing it.

On TrapezoidSynth, every single modulation is already bounded with `std::clamp()` or equivalent. So at least it won't blow up.

**Comment by ryukau** [comment]
Beat option is added to TrapezoidSynth in latest commit. To enable, drag `Free` option menu in LFO section. If it's not working correctly, please let me know.

Crossfade strategy doesn't sound as good as the synth in the video. It sounds more like Beat2 rather than Beat1. Probably something like below is a bit better:

```
truePhase = fmod(t, λ_t) / λ_t
diff = truePhase - phase
phase += deltaPhase + 0.01 * diff // 0.01 is arbitrary number in [0, 1).
phase -= floor(phase)             // Wrap around.
```

I'll look more into this topic when I make another LFO, but I'll change priority to other things for now. Thanks for the idea.

P.S. LFO tempo sync is now added to all possible synth/FX.

**Comment by magnetophon** [comment]
Thank you! It builds, but I havent gotten around to testing yet.
I will keep you up to date!

**Comment by ryukau** [comment]
Thanks for confirmation. I'll close this issue.

If you find a bug in tempo sync, feel free to reopen or make another issue.
